dist: trusty
language: node_js
node_js:
  - '10'
install:
  - npm install -g codecov
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then codecov; fi
deploy:
  provider: npm
  email: john@neetgroup.net
  api_key:
    secure: glLrtIalFeGGkNU55zbnjyNzMcaO6c2gC1EB7ZAtDl0L8cRgsuMbnA90MwYqqT39UWo8Cx9EWgPBBNx/kZu3SxLQiY7zjEsh00BfccK3B1ChxUAnmQ/OR9f7cSeceGJdp0OPrIrScU1ewD58gM2z6TbyKq9Lc6uEWKbVNw13FNv9qKmjGba4Cb9oZopVeSsvRVB4MDLzYGgQDzgdCGQMPRCPge1nPeItGoiJ3EpLLXaQX/F6MJ77aaBkGIVobi0+4xFwz2SQfeJbe9tt0bi3z9+Jge+ANSrlQ6DwuF12m//BkT+ZjdTTwj79haY1CX2QVEmnTEGTVVNxV4NpTB00xp047tOq2GesSnowjl5uu2/600ppMQ3yeoWY050ZziqMldwyExq0IrZXDit93L6gwEr8ui50yksAKhYm8kJxGd3d5qoW/WpVm0uYEZLhiiyRtCKRTsfFyE9cQFJoyERJtPVwAIkk90hinDI3D1kVVVbmSvqcg9d/5vFI610gJVqHHe1lyxv170rGhhPMIe74rzXY6D5MvCOCy30KiGsi/0xuAFwWXrEP8uZtXYuiXYt0k6UcktlbYnlSa/AaAo3IRRX5B3J3WymQ7vYrMEg0FAIDeoPF/dOYVES1ER1487vJNkurmp+EFRGyBofUYwY78CO19MnwEVlV5mFsQ7p1t9U=
  on:
    branch: master
